### PR TITLE
add sizehints to lin+quad value adding, supply a pairwise reduce

### PR DESCRIPTION
**Pull request by exaexa**
@stelmo can you benchmark this on your usecase?

### CODE REVIEW

**Comment by stelmo** [comment]
This helps, but adding quadratic constraints is still relatively slow (16 s -> 11 s in my case)

**Comment by exaexa** [comment]
@stelmo ok I'll add the fast reducer thingy

**Comment by exaexa** [comment]
@stelmo can you please benchmark again with replacing the `sum(x)` by `preduce(+, x)` ?

**Comment by stelmo** [comment]
This fixes it, nice :)

**Pull request merged**
