### PR TITLE
generalize the types in bounds

### PR DESCRIPTION
**Pull request by stelmo**

### CODE REVIEW

**Comment by stelmo** [comment]
Major change: Between no longer gets a default of infinity... Not sure if all types implement some sort if `infinity(T)` function

**Comment by exaexa** [comment]
I'll rebase and finish this

**Comment by exaexa** [comment]
> Major change: Between no longer gets a default of infinity... Not sure if all types implement some sort if `infinity(T)` function

Yeah it's typemax&typemin. Not sure about _all_ types but that's quite a strong requirement anyway.

What's worse that `BetweenT` can now not assume that the values will compare with `<` (so that it can put them into the correct order). So there's a bit of new logic there. Should be sufficiently compatible.

**Review by exaexa — APPROVED** [review]
looks ok now

**Pull request merged**
