### PR TITLE
Finish up TODOs in QV types

### PR DESCRIPTION
**Pull request by stelmo**

### CODE REVIEW

**Comment by stelmo** [comment]
Hmm getting a weird bug:
```julia
julia> t = LinearValueT(Expression(2)) + QuadraticValueT(Expression(2))
ERROR: MethodError: no method matching QuadraticValueT{FastDifferentiation.Node}(::LinearValueT{FastDifferentiation.Node})
The type `QuadraticValueT{FastDifferentiation.Node}` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  (::Type{QuadraticValueT{T}} where T)(::Any, ::Any)
   @ ConstraintTrees C:\Users\stelmo\.julia\packages\ConstraintTrees\AhePm\src\quadratic_value.jl:34
  QuadraticValueT{T}(; idxs, weights) where T
   @ ConstraintTrees C:\Users\stelmo\.julia\packages\ConstraintTrees\AhePm\src\quadratic_value.jl:33

Stacktrace:
 [1] +(a::LinearValueT{FastDifferentiation.Node}, b::QuadraticValueT{FastDifferentiation.Node})
   @ ConstraintTrees C:\Users\stelmo\.julia\packages\ConstraintTrees\AhePm\src\quadratic_value.jl:100        
 [2] top-level scope
   @ REPL[30]:1
```

**Comment by exaexa** [comment]
I removed some (many) explicit UnionAlls.

It seems to work now at least for:
```julia
julia> C.LinearValueT(1) - C.QuadraticValueT(2)
ConstraintTrees.QuadraticValueT{Int64}([(0, 0)], [-1])
```

If something still fails we should have a test for it (so that there's something to make sure it stays fixed).

**Comment by exaexa** [comment]
PS we could do type promotion at the place for `+` but let's avoid that for now unless we find an actual reason.

**Review by exaexa — APPROVED** [review]
LGTM but I expect this won't be sufficient.

**Comment by stelmo** [comment]
Merging, and I will report back as I find stuff in Diffmet

**Pull request merged**
